### ISSUE TITLE
Visualizing Filters

### ISSUE THREAD

**Issue by aferriss** [soumith/dcgan.torch#13]
How would one go about visualizing the filters of this network? I tried doing something like 

net = util.load(opt.net, opt.gpu)
filters = net:get(13).weight
image.save("filters.png", image.toDisplayTensor{input=filters})

The output is super tiny on this layer though, 24x44 pixels.
![2016_02_16_09 09 08](https://cloud.githubusercontent.com/assets/3698659/13086518/642ef686-d498-11e5-91fd-e999d20b0782.png)

How can I visualize more of the learned filters from other layers of the network? It looks like the conv layers are 1, 4, 7, 10, and 13.

Sampling from the other layers seems like it just outputs noise. Also looks like most of the other examples for visualizing conv layer filters are using the itorch image function, and I'd like to do it outside the interactive notebook if possible.

**Comment by soumith** [comment]
image.scale will help scale up the visualization.
image.save (as you have seen) will help visualize outside interactive notebook.
Otherwise, the display package will also work, as seen in the dcgan.torch code

**Comment by aferriss** [comment]
I think I am misunderstanding how these weights can be visualized. Is the image I posted above the entire set of kernels for that layer? I'm not sure I understand exactly how to project the other layers into pixel space. For instance if I take the first conv layer (weight:size = 100x1024x4x4), does it need to be narrowed to a three channel mapping as:

filters=net:get(1).weight
filters=filters:narrow(2, 1, 3)
image.toDisplayTensor{input=filters}
image.save("filters.png", filters)

And then, how would I visualize the features that are maximally activated by the training data? I guess I am looking at the [deconvnet paper](https://www.cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf) and wonder if there are any examples of this in torch?

**Comment by soumith** [comment]
the filters from other layers have to be visualized as single-channel images.
so, reshape weight to become size: 100 * 1024 x 4 x 4
