### ISSUE TITLE
what's dataset in 'DATA_ROOT=celebA dataset=folder th main.lu'?

### ISSUE THREAD

**Issue by loveJasmine** [soumith/dcgan.torch#18]
after done
 'DATA_ROOT=/media/envy/data1t/os_prj/github/DCGAN-tensorflow/data/celebA/img_align_celeba  th main.lua'

what's the next move

**Comment by soumith** [comment]
you could stand up from your chair and clap your hands ;)

**Comment by loveJasmine** [comment]
dataset=folder
I misunderstand that the value of dataset 'folder' must be substitute a existing folder

I think dataset='folder' is  good
