### ISSUE TITLE
Problems with installing cunn / cutorch

### ISSUE THREAD

**Issue by stml** [soumith/dcgan.torch#23]
Hello - I've been working to get the face examples running on OSX. I've used Torch before, but new to DCGANs.

After running through the full install a couple of times, including completely re-installing Torch (and trying [cltorch](https://github.com/hughperkins/cltorch), before reverting to Torch) I am still having problems.

Running `DATA_ROOT=celebA dataset=folder th main.lua` results in the following error:

`/Users/james/torch/install/bin/luajit: /Users/james/torch/install/share/lua/5.1/trepl/init.lua:384: module 'cunn' not found:No LuaRocks module found for cunn
	no field package.preload['cunn']
	no file '/Users/james/.luarocks/share/lua/5.1/cunn.lua'
	no file '/Users/james/.luarocks/share/lua/5.1/cunn/init.lua'
	no file '/Users/james/torch/install/share/lua/5.1/cunn.lua'
	no file '/Users/james/torch/install/share/lua/5.1/cunn/init.lua'
	no file '/Users/james/torch-cl/install/share/lua/5.1/cunn.lua'
	no file '/Users/james/torch-cl/install/share/lua/5.1/cunn/init.lua'
	no file './cunn.lua'
	no file '/Users/james/torch/install/share/luajit-2.1.0-beta1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn.lua'
	no file '/usr/local/share/lua/5.1/cunn/init.lua'
	no file '/Users/james/.luarocks/lib/lua/5.1/cunn.so'
	no file '/Users/james/torch/install/lib/lua/5.1/cunn.so'
	no file '/Users/james/torch/install/lib/cunn.dylib'
	no file '/Users/james/torch-cl/install/lib/cunn.dylib'
	no file '/Users/james/torch-cl/install/lib/lua/5.1/cunn.so'
	no file './cunn.so'
	no file '/usr/local/lib/lua/5.1/cunn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/Users/james/torch/install/share/lua/5.1/trepl/init.lua:384: in function 'require'
	main.lua:126: in main chunk
	[C]: in function 'dofile'
	...ames/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x0109892d10
`

Running `luarocks install cunn` fails when it tries to install cutorch:

`CMake Error at /usr/local/Cellar/cmake/3.6.0/share/cmake/Modules/FindCUDA.cmake:619 (message):
  Specify CUDA_TOOLKIT_ROOT_DIR
Call Stack (most recent call first):
  CMakeLists.txt:7 (FIND_PACKAGE)
-- Configuring incomplete, errors occurred!
See also "/tmp/luarocks_cutorch-scm-1-5945/cutorch/build/CMakeFiles/CMakeOutput.log".
Error: Failed installing dependency: https://raw.githubusercontent.com/torch/rocks/master/cutorch-scm-1.rockspec - Build error: Failed building.
`

As I understand it, CUDA requires a GPU, which I don't have - but the instructions for dcgan.torch suggest that a GPU isn't necessary, so I believe there should be a way around this?

Many thanks.

**Comment by soumith** [comment]
hi! while the need for GPUs isn't essential for training DCGANs, it is practically needed. Training DCGANs on CPU will take months.

The gpu=0 flag will let you train DCGANs without the GPU.
The generation scripts, which use pre-trained models are more suited to try out when you dont have a GPU.
https://github.com/soumith/dcgan.torch#2-use-a-pre-trained-generator-to-generate-images

**Comment by stml** [comment]
Thanks for the swift reply. I appreciate the length of time, and am planning to move to AWS, but just making sure I understand how everything works.

Now training with the command (for others' reference):

`gpu=0 DATA_ROOT=celebA dataset=folder th main.lua`
