### ISSUE TITLE
unknown Torch class <torch.CudaTensor> 

### ISSUE THREAD

**Issue by paperkettle** [soumith/dcgan.torch#28]
Hey - having some issues getting this running, would greatly appreciate some other eyes on this as I'm still young in my deep learning understanding.

It appears that I'm successfully able to generate checkpoints using
`DATA_ROOT=500 dataset=folder gpu=1 th main.lua`

I'm running a GTX 1080 with CUDA 8.0, and I get a folder full of checkpoints. 

But when I try to run generate.lua, I get 
"unknown Torch class <torch.CudaTensor>" errors. 

Any thoughts? Here is what I'm seeing. Any tips would be majorly appreciated!

```
gpu=1 net=checkpoints/experiment1_10_net_G.t7 th generate.lua
{
  gpu : 1
  noisemode : "random"
  name : "generation1"
  noisetype : "normal"
  batchSize : 32
  net : "checkpoints/experiment1_10_net_G.t7"
  imsize : 1
  nz : 100
  display : 1
}
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/torch/File.lua:343: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
	/root/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
	/root/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
	/root/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
	generate.lua:24: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```

**Comment by Guim3** [comment]
This happened to me, too. The code is loading the generator which is stored as a cuda tensor before importing cunn and cudnn, so it doesn't recognize cuda tensors.
Just add this after opt is initialized:
`if opt.gpu > 0 then
require 'cunn';
require 'cudnn';
end
`

**Comment by paperkettle** [comment]
Thanks!! That did the trick!!!
