### ISSUE TITLE
The pixel value scales of fake and real images are different for discriminator

### ISSUE THREAD

**Issue by houxianxu** [soumith/dcgan.torch#42]
The pixel value of real images is from 0 to 1, and the value for fake images is from -1 to 1 because of `tanh` function. And the real images and fake images are used to train discriminator with different scales.

I wonder whether this design is on purpose, and is there any benefit we can get from this?

**Comment by soumith** [comment]
pixel values of real images is -1 to 1 too. they are mean-normalized
