### ISSUE TITLE
Effect of noise vector distribution on training and image generation

### ISSUE THREAD

**Issue by vasavig** [soumith/dcgan.torch#44]
Hi,

I am trying to understand how the distribution of Z vector affects the training and the subsequent generation of images from the trained generator. The paper hasn't mentioned any significant effects of using different kinds of distributions to sample Z vectors from. From my experiments, I found that it matters a lot for the quality and type of images generated. For example, the following are some images generated after training the DCGAN on Celeb dataset for 25 iterations using  uniform(0,1) distribution for sampling the Z vectors.

![25](https://cloud.githubusercontent.com/assets/4658916/19714351/6df31e3c-9b1b-11e6-855b-0e8b6af37973.png)

Also, after training the DCGAN on a normal(0,1) distribution, the corresponding trained generator's results on a Z vector not sampled from this normal distribution weren't good.

Can anyone give any tips on choosing the right kind of distribution for Z vector sampling based on the kind of training data we use?

**Comment by soumith** [comment]
you should choose a normal distribution.
Tom White gives a good set of arguments here: https://github.com/soumith/dcgan.torch/issues/14 as well as in his latest paper.
