### ISSUE TITLE
could not find any image file in the given input paths

### ISSUE THREAD

**Issue by tjusxh** [soumith/dcgan.torch#45]
$:~/dcgan.torch$ ls
arithmetic.lua  cache  cohnExtent  data  generate.lua  images  INSTALL.md  LICENSE.md  main.lua  PATENTS  README.md
$:~/dcgan.torch$ DATA_ROOT=cohnExtent dataset=folder th main.lua

In root directory, I make the file path cohnExtent and put some images in the directory. But When I run the command, the error like:
$/torch/install/bin/luajit: ...e/$/torch/install/share/lua/5.1/threads/threads.lua:255: 
[thread 2 callback] $/dcgan.torch/data/dataset.lua:202: Could not find any image file in the given input paths
[thread 4 callback] $/dcgan.torch/data/dataset.lua:202: Could not find any image file in the given input paths
[thread 1 callback] $/dcgan.torch/data/dataset.lua:202: Could not find any image file in the given input paths
[thread 3 callback]$/dcgan.torch/data/dataset.lua:202: Could not find any image file in the given input paths

**Comment by soumith** [comment]
it looks for images with the following extensions https://github.com/soumith/dcgan.torch/blob/master/data/dataset.lua#L146

maybe it did not find any such.
