### ISSUE TITLE
which lua version is suitable?

### ISSUE THREAD

**Issue by tjusxh** [soumith/dcgan.torch#46]
When I run DATA_ROOT=xxx  dataset=folder th main.sh
I get the information:
[C]: in function 'xpcall'
    /home/xhs/torch/install/share/lua/5.1/threads/threads.lua:234: in function 'callback'
    /home/xhs/torch/install/share/lua/5.1/threads/queue.lua:65: in function </home/xhs/torch/install/share/lua/5.1/threads/queue.lua:41>
    [C]: in function 'pcall'
    /home/xhs/torch/install/share/lua/5.1/threads/queue.lua:40: in function 'dojob'
    [string "  local Queue = require 'threads.queue'..."]:13: in main chunk
stack traceback:
    [C]: in function 'error'
    /home/xhs/torch/install/share/lua/5.1/threads/threads.lua:183: in function 'dojob'
    /home/xhs/torch/install/share/lua/5.1/threads/threads.lua:264: in function 'synchronize'
    /home/xhs/torch/install/share/lua/5.1/threads/threads.lua:142: in function 'specific'
    /home/xhs/torch/install/share/lua/5.1/threads/threads.lua:125: in function 'Threads'
    /home/xhs/dcgan.torch/data/data.lua:30: in function 'new'
    main.lua:38: in main chunk
    [C]: in function 'dofile'
    .../xhs/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk

by google I find if the version is not matching? How to solve the question?Thank you!

**Comment by soumith** [comment]
well, DATA_ROOT=xxx is an example of a folder. replace it with the path to the folder where your dataset lies.
