### ISSUE TITLE
Confusing dimension of first generator layer( 4x4x512 ? )

### ISSUE THREAD

**Issue by NySunShine** [soumith/dcgan.torch#55]
In the paper, the input of generator Z (100 x 1) is projected to 4 x 4 x 1024 ( exactly reshape ).
However, as I understood, the input Z is projected to 4 x 4 x 512 in this code.
I think it is not important whether 1024 or not, but I'm wondering about this.
Thanks

**Comment by soumith** [comment]
it depends on which experiment you refer to from the paper. some used 512 some 1024
