### ISSUE TITLE
error in running th main.lua

### ISSUE THREAD

**Issue by royal-feng** [soumith/dcgan.torch#56]
/home/royal-feng/torch/install/share/lua/5.1/xlua/init.lua:360: module 'libjpeg' not found:
	no field package.preload['libjpeg']
	no file '/home/royal-feng/.luarocks/share/lua/5.1/libjpeg.lua'
	no file '/home/royal-feng/.luarocks/share/lua/5.1/libjpeg/init.lua'
	no file '/home/royal-feng/torch/install/share/lua/5.1/libjpeg.lua'
	no file '/home/royal-feng/torch/install/share/lua/5.1/libjpeg/init.lua'
	no file './libjpeg.lua'
	no file '/home/royal-feng/torch/install/share/luajit-2.1.0-beta1/libjpeg.lua'
	no file '/usr/local/share/lua/5.1/libjpeg.lua'
	no file '/usr/local/share/lua/5.1/libjpeg/init.lua'
	no file '/home/royal-feng/torch/install/lib/libjpeg.so'
	no file '/home/royal-feng/.luarocks/lib/lua/5.1/libjpeg.so'
	no file '/home/royal-feng/torch/install/lib/lua/5.1/libjpeg.so'
	no file './libjpeg.so'
	no file '/usr/local/lib/lua/5.1/libjpeg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
warning: <libjpeg> could not be loaded (is it installed?)
/home/royal-feng/torch/install/share/lua/5.1/xlua/init.lua:360: module 'libjpeg' not found:
	no field package.preload['libjpeg']
	no file '/home/royal-feng/.luarocks/share/lua/5.1/libjpeg.lua'
	no file '/home/royal-feng/.luarocks/share/lua/5.1/libjpeg/init.lua'
	no file '/home/royal-feng/torch/install/share/lua/5.1/libjpeg.lua'
	no file '/home/royal-feng/torch/install/share/lua/5.1/libjpeg/init.lua'
	no file './libjpeg.lua'
	no file '/home/royal-feng/torch/install/share/luajit-2.1.0-beta1/libjpeg.lua'
	no file '/usr/local/share/lua/5.1/libjpeg.lua'
	no file '/usr/local/share/lua/5.1/libjpeg/init.lua'
	no file '/home/royal-feng/torch/install/lib/libjpeg.so'
	no file '/home/royal-feng/.luarocks/lib/lua/5.1/libjpeg.so'
	no file '/home/royal-feng/torch/install/lib/lua/5.1/libjpeg.so'
	no file './libjpeg.so'
	no file '/usr/local/lib/lua/5.1/libjpeg.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
warning: <libjpeg> could not be loaded (is it installed?)

And when I try luarocks install libjpeg ,it return No results matching query were found.

**Comment by royal-feng** [comment]
sorry ,I have  solve the low level error ...

**Comment by soumith** [comment]
ok glad you solved it
