### ISSUE TITLE
Generator errors with user set

### ISSUE THREAD

**Issue by michaelByrne** [soumith/dcgan.torch#58]
Hallo, 

Sorry to be a bother. 

I feel like I've tried this every way imaginable with the same negative results. 

I'm attempting to run my own generator trained on a small (~200) sample set of images (expecting a poor output, but just to verify that I have things running properly). Running the generator script always returns an error of the following: 

/home/ubuntu/torch/install/bin/luajit: cannot open <experiment1_9_net_G.t7> in mode r  at /home/ubuntu/torch/pkg/torch/lib/TH/THDiskFile.c:649

The file is correctly referred to and has the proper permissions. I've tried loading the same file in the repl with a basic torch.load() and also just running line by line through the generator script. Using the same steps with the pretrained bedrooms model will not yield the same error, so I have to think that I'm giving it the wrong t7 file or have failed in creating the right t7 file.

Any help is appreciated. 

thanks, 

- michael

**Comment by michaelByrne** [comment]
problem solved: larger image set successfully trained

**Comment by JohnHammell** [comment]
> problem solved: larger image set successfully trained

Hi @michaelByrne ,

As it's been a while since your last update here, I'm hoping that you recall what you did in order to get this working correctly.

I'm getting the same errors as you describe.

Thanks in advance for any insight into the issue.
