### ISSUE TITLE
image size //

### ISSUE THREAD

**Issue by kenkroft** [soumith/dcgan.torch#59]
Hello !

Thanks for this it's amazing. But I'd really like to train on bigger images, but when I try to modify main.lua size parameters (   batchSize = 64,
   loadSize = 96,
   fineSize = 64, )

I get this error 

n/torch/install/share/lua/5.1/nn/BCECriterion.lua:24: input and target size mismatch
stack traceback:
	[C]: in function 'assert'
	.../corepan/torch/install/share/lua/5.1/nn/BCECriterion.lua:24: in function 'forward'
	main.lua:163: in function 'opfunc'
	/home/corepan/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	main.lua:213: in main chunk
	[C]: in function 'dofile'
	...epan/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00405d50

Someone have a clue for me (: ?
Thanks !

**Comment by soumith** [comment]
have a look at this thread, it'll answer your questions: https://github.com/soumith/dcgan.torch/issues/2#issuecomment-164862299

**Comment by kenkroft** [comment]
woah thanks for that fast answer, I'm going on it now

**Comment by kenkroft** [comment]
Okay, so I don't get everything on that thread but I'll try to manage the 128x128 .
But, just curious, if I wanted to have like 1920x1080 generations, would it be possible ? Or is it just unrealistic dream ?

**Comment by soumith** [comment]
wrt GANs at the moment, 1920x1080 is an unrealistic dream. We cant even do 256x256 reasonably on a diverse set of problems.

**Comment by kenkroft** [comment]
I saw that person : https://github.com/hardmaru/cppn-gan-vae-tensorflow reffering to your code as an inspiration. So I was thinking maybe. Anyway, thanks so much for everything (:

**Comment by soumith** [comment]
you can implement a VAE-GAN and maybe produce a 512px on MNIST, but that's about it. Open research :)
