### ISSUE TITLE
attempt to call noBias (a nil value)

### ISSUE THREAD

**Issue by sanealytics** [soumith/dcgan.torch#60]
Hi there,

I am trying to train this on my data. I put it under a subdirectory after noting a closed issue. It can now read my files, but I still get the following error -

```
saurabh@neuralnets:~/Documents/Code/dcgan.torch$ DATA_ROOT=/media/saurabh/ssdfast/myphotos dataset=folder th main.lua
{
  ntrain : inf
  beta1 : 0.5
  name : "experiment1"
  niter : 25
  batchSize : 64
  ndf : 64
  fineSize : 64
  nz : 100
  loadSize : 96
  gpu : 1
  ngf : 64
  dataset : "folder"
  lr : 0.0002
  noise : "normal"
  nThreads : 4
  display_id : 10
  display : 1
}
Random Seed: 3827	
Starting donkey with id: 1 seed: 3828
table: 0x41ec15c8
Starting donkey with id: 2 seed: 3829
table: 0x41630f80
Starting donkey with id: 3 seed: 3830
table: 0x41e848a0
Starting donkey with id: 4 seed: 3831
table: 0x40bef428
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Loading train metadata from cache
Dataset: folder	 Size: 	168950	
/home/saurabh/torch/install/bin/luajit: main.lua:45: attempt to call method 'noBias' (a nil value)
stack traceback:
	main.lua:45: in function 'callback'
	/home/saurabh/torch/install/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	/home/saurabh/torch/install/share/lua/5.1/nn/Module.lua:322: in function 'apply'
	main.lua:81: in main chunk
	[C]: in function 'dofile'
	...rabh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```

Any pointers on what I'm missing here are greatly appreciated.

**Comment by sanealytics** [comment]
I upgraded everything (torch, nn, cudnn, optim)... thought issue was with an outdated nn library. Now, I get the following error -

```
Dataset: folder	 Size: 	168950	
/home/saurabh/torch/install/bin/luajit: /home/saurabh/torch/install/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
/home/saurabh/torch/install/share/lua/5.1/nn/THNN.lua:110: bad argument #4 to 'v' (weight tensor must be 2D (nOutputPlane,nInputPlane*kH*kW) at /tmp/luarocks_cunn-scm-1-6954/cunn/lib/THCUNN/SpatialConvolutionMM.cu:13)
stack traceback:
	[C]: in function 'v'
	/home/saurabh/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	...bh/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function <...bh/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/home/saurabh/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/home/saurabh/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	main.lua:162: in function 'opfunc'
	/home/saurabh/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	main.lua:213: in main chunk
	[C]: in function 'dofile'
	...rabh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/home/saurabh/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/home/saurabh/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	main.lua:162: in function 'opfunc'
	/home/saurabh/torch/install/share/lua/5.1/optim/adam.lua:37: in function 'adam'
	main.lua:213: in main chunk
	[C]: in function 'dofile'
	...rabh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670

```

I'm out of ideas at the moment. Would appreciate any pointers on where to look.

**Comment by soumith** [comment]
update cutorch and cunn :)

luarocks install cutorch
luarocks install cunn

**Comment by sanealytics** [comment]
Oh God! That's it... thanks! :flushed: 

I created this script so that I don't forget to do this again (has happened before) -

```
$ cat ~/update_torch.sh 
#!/bin/bash

cat packages.torch | while read package
do
  echo updating $package
  luarocks install $package
done

echo "You are now free to have some fun"

```

**Comment by soumith** [comment]
we have an update script in ~/torch for this precise reason. To update the core packages, one simply has to do:
cd ~/torch
./clean.sh
./update.sh

**Comment by tyashima** [comment]
I had the same problem when running the code for church_outdoor dataset (on Ubuntu 14.04).
I updated all the packages concerned with this issue (cleaned up torch and re-installed it again), 
but still got the error.

Error detail is;

{
  ntrain : inf
  beta1 : 0.5
  name : "experiment1"
  niter : 25
  batchSize : 64
  ndf : 64
  fineSize : 64
  nz : 100
  loadSize : 96
  gpu : 1
  ngf : 64
  dataset : "lsun"
  lr : 0.0002
  noise : "normal"
  nThreads : 4
  display_id : 10
  display : 1
}
Random Seed: 4252	
Starting donkey with id: 2 seed: 4254
table: 0x4074fa48
Starting donkey with id: 1 seed: 4253
table: 0x41f07c00
Starting donkey with id: 4 seed: 4256
table: 0x40305f48
Starting donkey with id: 3 seed: 4255
table: 0x40b27350
Classes:
1	church_outdoor
Classes:
1	church_outdoor
Classes:
Classes:
1	church_outdoor
1	church_outdoor
initializing train loader
initializing: 	church_outdoor
initializing train loader
initializing: 	church_outdoor
initializing train loader
initializing: 	church_outdoor
initializing train loader
initializing: 	church_outdoor
Dataset: lsun	 Size: 	126227	
/home/yashima/torch/install/bin/luajit: main.lua:45: attempt to call method 'noBias' (a nil value)
stack traceback:
	main.lua:45: in function 'callback'
	/home/yashima/.luarocks/share/lua/5.1/nn/Module.lua:318: in function 'apply'
	/home/yashima/.luarocks/share/lua/5.1/nn/Module.lua:322: in function 'apply'
	main.lua:81: in main chunk
	[C]: in function 'dofile'
	...hima/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670


Any comments would be appreciated. Thanks.
