### ISSUE TITLE
Does there exists any version for pytorch or tensorflow?

### ISSUE THREAD

**Issue by coderSkyChen** [soumith/dcgan.torch#82]
Hi,
It's very nice for you to open source your torch7 code.
However, i'm new to torch7 and lua, it's distressted to learn a new AI tool for this project....

**Comment by coderSkyChen** [comment]
I've found. 
Thanks.

**Comment by adv-ai-tech** [comment]
@coderSkyChen  Can you please share the link. I am not able to find
