### ISSUE TITLE
Disable saving checkpoints after each epoch

### ISSUE THREAD

**Issue by jonaslund** [soumith/dcgan.torch#85]
How can I set the training to only save the checkpoint for each Nth epoch. Let's say I only want to save the checkpoint for each 100th epoch iteration to save hard drive space.

**Comment by jshaw** [comment]
I've been needing this functionality when training on small data sets... @jonaslund, I've made a pull request on this repo but if you still need this, my fork has this option available now.

**Comment by soumith** [comment]
fixed via https://github.com/soumith/dcgan.torch/pull/91
